ALTER TABLE jobs

ADD COLUMN IF NOT EXISTS last_error TEXT;


ALTER TABLE jobs

ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();


ALTER TABLE jobs

ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
