ALTER TABLE plans
ALTER COLUMN created_at TYPE TIMESTAMPTZ
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE tenants
ALTER COLUMN created_at TYPE TIMESTAMPTZ
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE jobs
ALTER COLUMN lease_expires_at TYPE TIMESTAMPTZ
USING lease_expires_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at TYPE TIMESTAMPTZ
USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN started_at TYPE TIMESTAMPTZ
USING started_at AT TIME ZONE 'UTC',
ALTER COLUMN completed_at TYPE TIMESTAMPTZ
USING completed_at AT TIME ZONE 'UTC',
ALTER COLUMN updated_at TYPE TIMESTAMPTZ
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE job_attempts
ALTER COLUMN started_at TYPE TIMESTAMPTZ
USING started_at AT TIME ZONE 'UTC',
ALTER COLUMN finished_at TYPE TIMESTAMPTZ
USING finished_at AT TIME ZONE 'UTC';

ALTER TABLE dead_letter_jobs
ALTER COLUMN failed_at TYPE TIMESTAMPTZ
USING failed_at AT TIME ZONE 'UTC';
